-keep class com.dexterous.flutterlocalnotifications.** { *; }
-keep class id.flutter.flutter_background_service.** { *; }
-keepattributes *Annotation*
-keep class androidx.core.app.NotificationCompat** { *; }
